app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(navbar = "Sensitivity analysis for the percentage of meaningfully strong effects")
app$uploadFile(calibrated_uploaddat = "gbc_prepped.csv")
app$setInputs(`calibrated_yi.name` = "yi")
app$setInputs(`calibrated_vi.name` = "vi")
app$setInputs(calibrated_muB = 1)
app$setInputs(calibrated_q = character(0))
app$setInputs(calibrated_q = 0.9)
app$setInputs(calibrated_r = character(0))
app$setInputs(calibrated_r = 0.1)
app$setInputs(calibrated_tail = "below")
app$setInputs(calibrated_R = 500)
app$setInputs(calibrated_calculate = "click")
app$setInputs(calibrated_plot = "click")
app$snapshot()
app$setInputs(calibrated_muB = 0.5)
app$setInputs(calibrated_q = 0.5)
app$setInputs(calibrated_r = 0.5)
app$setInputs(calibrated_tail = "above")
app$setInputs(calibrated_calculate = "click")
app$setInputs(calibrated_Bmax = 6)
app$setInputs(calibrated_plot = "click")
app$snapshot()
app$setInputs(calibrated_muB = -0.6931472)
app$setInputs(calibrated_q = -0.6931472)
app$setInputs(calibrated_calculate = "click")
app$setInputs(calibrated_scale = "Log-RR")
app$setInputs(calibrated_calculate = "click")
app$snapshot()
app$setInputs(calibrated_scale = "RR")
app$setInputs(`calibrated_vi.name` = "vyi")
app$setInputs(calibrated_muB = 1.5)
app$setInputs(calibrated_q = 0.5)
app$setInputs(calibrated_R = 2000)
app$setInputs(calibrated_calculate = "click")
app$snapshot()
app$uploadFile(calibrated_uploaddat = "flegal_prepped.csv")
app$setInputs(calibrated_scale = "Log-RR")
app$setInputs(`calibrated_vi.name` = "vi")
app$setInputs(calibrated_muB = 0)
app$setInputs(calibrated_muB = 0.5)
app$setInputs(calibrated_q = -0.6931472)
app$setInputs(calibrated_R = 500)
app$setInputs(calibrated_calculate = "click")
app$setInputs(calibrated_plot = "click")
app$snapshot()
app$setInputs(calibrated_scale = "RR")
app$setInputs(calibrated_muB = 1.5)
app$setInputs(calibrated_q = 0.5)
app$setInputs(calibrated_r = 0.1)
app$setInputs(calibrated_calculate = "click")
app$snapshot()
app$setInputs(calibrated_scale = "Log-RR")
app$setInputs(calibrated_q = -0.6931472)
app$setInputs(calibrated_muB = 0.4054651)
app$setInputs(calibrated_calculate = "click")
app$snapshot()
app$setInputs(calibrated_scale = "RR")
app$setInputs(calibrated_muB = 1)
app$setInputs(calibrated_q = 1.2)
app$setInputs(calibrated_r = 1)
app$setInputs(calibrated_calculate = "click")
app$snapshot()
app$uploadFile(calibrated_uploaddat = "data_calib_test_1-1.csv")
app$setInputs(`calibrated_yi.name` = "est")
app$setInputs(`calibrated_vi.name` = "var")
app$setInputs(calibrated_q = 0)
app$setInputs(calibrated_r = 0)
app$setInputs(calibrated_R = 0)
app$setInputs(calibrated_calculate = "click")
app$setInputs(calibrated_Bmin = 0)
app$setInputs(calibrated_Bmax = 0)
app$setInputs(calibrated_plot = "click")
app$snapshot()
app$setInputs(intab = "Parametric estimation (allows heterogeneous bias)")
app$setInputs(parametric_yr = 1.2)
app$setInputs(parametric_vyr = character(0))
app$setInputs(parametric_vyr = 0.01)
app$setInputs(parametric_t2 = character(0))
app$setInputs(parametric_t2 = 0.1)
app$setInputs(parametric_vt2 = character(0))
app$setInputs(parametric_vt2 = 0.01)
app$setInputs(parametric_muB = character(0))
app$setInputs(parametric_muB = 1)
app$setInputs(parametric_muB = 1.2)
app$setInputs(parametric_prop_t2 = character(0))
app$setInputs(parametric_prop_t2 = 0.35)
app$setInputs(parametric_r = character(0))
app$setInputs(parametric_r = 0.2)
app$setInputs(parametric_q = character(0))
app$setInputs(parametric_q = 1.1)
app$setInputs(parametric_calculate = "click")
app$setInputs(parametric_plot = "click")
app$snapshot()
app$setInputs(parametric_scale = "Log-RR")
app$setInputs(parametric_q = 0.09531018)
app$setInputs(parametric_muB = 0.1823216)
app$setInputs(parametric_yr = 0.1823216)
app$setInputs(parametric_calculate = "click")
app$setInputs(parametric_plot = "click")
app$snapshot()
app$setInputs(parametric_scale = "RR")
app$setInputs(parametric_yr = 0)
app$setInputs(parametric_vyr = 0)
app$setInputs(parametric_t2 = 0)
app$setInputs(parametric_vt2 = 0)
app$setInputs(parametric_muB = 0)
app$setInputs(parametric_prop_t2 = 0)
app$setInputs(parametric_r = 0)
app$setInputs(parametric_q = 0)
app$setInputs(parametric_calculate = "click")
app$setInputs(parametric_Bmin = 0)
app$setInputs(parametric_Bmax = 0)
app$setInputs(parametric_plot = "click")
app$snapshot()
app$setInputs(parametric_yr = 1.5)
app$setInputs(parametric_vyr = 0.5)
app$setInputs(parametric_t2 = 0.25)
app$setInputs(parametric_vt2 = 0.5)
app$setInputs(parametric_muB = 1.5)
app$setInputs(parametric_prop_t2 = 0.5)
app$setInputs(parametric_r = 0.75)
app$setInputs(parametric_q = 0.5)
app$setInputs(parametric_tail = "below")
app$setInputs(parametric_calculate = "click")
app$setInputs(parametric_Bmin = 1)
app$setInputs(parametric_Bmax = 4)
app$setInputs(parametric_plot = "click")
app$snapshot()
app$setInputs(parametric_scale = "Log-RR")
app$setInputs(parametric_q = 0.1823216)
app$setInputs(parametric_r = 0.5)
app$setInputs(parametric_r = 0)
app$setInputs(parametric_r = 0.2)
app$setInputs(parametric_muB = character(0))
app$setInputs(parametric_muB = 0.2)
app$setInputs(parametric_prop_t2 = 0.15)
app$setInputs(parametric_yr = 0.4)
app$setInputs(parametric_vyr = 0.05)
app$setInputs(parametric_vt2 = 0.05)
app$setInputs(parametric_calculate = "click")
app$setInputs(parametric_Bmax = 1.791759)
app$setInputs(parametric_plot = "click")
app$snapshot()
app$setInputs(intab = "Robust estimation (homogeneous bias across studies)")
app$uploadFile(calibrated_uploaddat = "kodama_prepped.csv")
app$setInputs(`calibrated_yi.name` = "yi")
app$setInputs(`calibrated_vi.name` = "vi")
app$setInputs(calibrated_muB = 1.5)
app$setInputs(calibrated_q = 1.5)
app$setInputs(calibrated_r = 0.3)
app$setInputs(calibrated_tail = "below")
app$setInputs(calibrated_R = character(0))
app$setInputs(calibrated_calculate = "click")
app$setInputs(calibrated_calculate = "click")
app$snapshot()
