name: Build Shiny Docker Image and Deploy to Heroku

# Set here what events should trigger the action
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # copy folder containing the app to the root of the repo
      # this is needed b/c setting dockerfile_directory is not working
      - name: Change directory
        run: 'cp -R main-site/* .'

      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.2.1
        with:

          # The email address associated with your Heroku account.
          email: ${{ secrets.HEROKU_EMAIL }}

          # Heroku API key associated with provided user's email.
          # Api Key is available under your Heroku account settings.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # Dokerfile name. Optional, by default will be set to "Dockerfile".
          dockerfile_name: Dockerfile

          # Additional options of docker build command. (Optional)
          docker_options: "--no-cache"

          # Dokerfile directory.
          # For example, if you have a Dockerfile in the root of your project, leave it as `./`
          dockerfile_directory: ./
